const TRANSCRIPT_RESPONSE = {
  id: '64szwo5je8-1046-45b7-ad48-2e72533793fa',
  language_model: 'assemblyai_default',
  acoustic_model: 'assemblyai_default',
  language_code: 'en_us',
  status: 'queued',
  audio_url: 'http://embed.wistia.com/deliveries/f7e0761102c4cd3f2beee99d5ac56a414d162372.bin',
  text: "strifn",
  words: null,
  // [{
  //   "text": "I'd",
  //   "start": 810,
  //   "end": 1018,
  //   "confidence": 0.99725,
  //   "speaker": null
  // },
  // {
  //   "text": "like",
  //   "start": 1034,
  //   "end": 1166,
  //   "confidence": 0.77728,
  //   "speaker": null
  // },
  // {
  //   "text": "to",
  //   "start": 1188,
  //   "end": 1326,
  //   "confidence": 1,
  //   "speaker": null
  // },
  // {
  //   "text": "talk",
  //   "start": 1348,
  //   "end": 1486,
  //   "confidence": 0.99992,
  //   "speaker": null
  // },]
  utterances: null,
  confidence: null,
  audio_duration: null,
  punctuate: true,
  format_text: true,
  dual_channel: null,
  webhook_url: null,
  webhook_status_code: null,
  webhook_auth: false,
  webhook_auth_header_name: null,
  speed_boost: false,
  auto_highlights_result: null,
  auto_highlights: false,
  audio_start_from: null,
  audio_end_at: null,
  word_boost: [],
  boost_param: null,
  filter_profanity: false,
  redact_pii: false,
  redact_pii_audio: false,
  redact_pii_audio_quality: null,
  redact_pii_policies: null,
  redact_pii_sub: null,
  speaker_labels: false,
  content_safety: false,
  iab_categories: false,
  content_safety_labels: {},
  iab_categories_result: {},
  language_detection: false,
  custom_spelling: null,
  throttled: null,
  auto_chapters: false,
  summarization: false,
  summary_type: null,
  summary_model: null,
  custom_topics: false,
  topics: [],
  speech_threshold: null,
  disfluencies: false,
  sentiment_analysis: false,
  sentiment_analysis_results: null,
  chapters: null,
  entity_detection: false,
  entities: null,
  speakers_expected: null
}

export type TTranscriptResponse = typeof TRANSCRIPT_RESPONSE;
